{
 "title": "Процент Null ценовых значений TQBR",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Активные алерты", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Процент Null значений цен тикеров TQBR за интервал времени",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (calculation_date + calculation_time) AT TIME ZONE 'Europe/Moscow' AS \"time\",\r\n  AVG(percent_null_prices) AS \"value\"\r\nFROM\r\n  null_price_percent_metrics\r\nWHERE\r\n  $__timeFilter(calculation_date + calculation_time AT TIME ZONE 'Europe/Moscow')\r\nGROUP BY \"time\"\r\nORDER BY \"time\" DESC"
    }
   ]
  },
  {
   "title": "Процент Null TQBR текущий",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  calculation_date + calculation_time AS \"time\",\r\n  percent_null_prices\r\nFROM\r\n  null_price_percent_metrics\r\nORDER BY\r\n  \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SBER price ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (quote_date + quote_time::time) AT TIME ZONE 'Europe/Moscow' AS \"time\",\r\n  price\r\nFROM\r\n  tqbr_prices\r\nWHERE\r\n  ticker = 'SBER'\r\nORDER BY\r\n  \"time\" DESC\r\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "ROSN price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (quote_date + quote_time::time) AT TIME ZONE 'Europe/Moscow' AS \"time\",\r\n  price\r\nFROM\r\n  tqbr_prices\r\nWHERE\r\n  ticker = 'ROSN'\r\nORDER BY\r\n  \"time\" DESC\r\nLIMIT 10000;"
    }
   ]
  },
  {
   "title": "MTLR price ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (quote_date + quote_time::time) AT TIME ZONE 'Europe/Moscow' AS \"time\",\r\n  price\r\nFROM\r\n  tqbr_prices\r\nWHERE\r\n  ticker = 'MTLR'\r\nORDER BY\r\n  \"time\" DESC\r\nLIMIT 10000;"
    }
   ]
  },
  {
   "title": "GAZP price ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (quote_date + quote_time::time) AT TIME ZONE 'Europe/Moscow' AS \"time\",\r\n  price\r\nFROM\r\n  tqbr_prices\r\nWHERE\r\n  ticker = 'GAZP'\r\nORDER BY\r\n  \"time\" DESC\r\nLIMIT 10000;"
    }
   ]
  }
 ]
}