version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_OS_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vlan1

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "${GF_OS_PORT}:${GF_DOCKER_PORT}"
    depends_on:
      - postgres
    networks:
      - vlan1

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_OS_PORT}:${APP_DOCKER_PORT}"
    depends_on:
      - postgres
      - grafana
    networks:
      - vlan1
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_DOCKER_HOST}
      DB_PORT: ${DB_DOCKER_PORT}

volumes:
  postgres_data:

networks:
  vlan1:
    driver: bridge