name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOSTNAME }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PORT: ${{ secrets.SERVER_SSH_PORT }}  
  SSH_KEY: ${{ secrets.KEY }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build app

      - name: Push Docker Images
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker compose -f docker-compose.yml push app
       
      - name: Install SSH Key
        uses: appleboy/ssh-action@master
        with:
          host: $SERVER_HOST
          username: $SERVER_USER
          key: $SSH_KEY
          port: $SERVER_PORT
          script: | 
            ls -la