name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOSTNAME }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PORT: $ {{ SERVER_SSH_PORT}}
  SSH_KEY: ${{ secrets.KEY }}
  SERVER_PASSWORD: $ {{ secrets.SERVER_PASSWORD }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build app

      - name: Push Docker Images
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker compose -f docker-compose.yml push app
       
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: SERVER_HOST
          user: SERVER_USER
          pass: SERVER_PASSWORD
          port: SERVER_PORT
          connect_timeout: 10s
          script: |
            (rm -rf /home/github/test || true)
            ls -la  
            echo "test" 
            mkdir -p /tmp/github/test/test1 && 
            mkdir -p /tmp/github/test/test2 &&